default_agent: strands_claude_getting_started
agents:
  strands_claude_getting_started:
    name: strands_claude_getting_started
    entrypoint: /Users/fengwei/src/fengwei/ai-agents-examples/01-strands-with-bedrock-model/strands_claude.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::996091555753:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-8556fc4504
      execution_role_auto_create: false
      account: '996091555753'
      region: us-east-1
      ecr_repository: 996091555753.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-strands_claude_getting_started
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: strands_claude_getting_started-lUN8xB8jtw
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:996091555753:runtime/strands_claude_getting_started-lUN8xB8jtw
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-strands_claude_getting_started-builder
      execution_role: arn:aws:iam::996091555753:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-8556fc4504
      source_bucket: bedrock-agentcore-codebuild-sources-996091555753-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
